# Generated by Django 5.2 on 2025-05-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject',
            new_name='course',
        ),
    ]
