# Generated by Django 5.2 on 2025-05-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_grade_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student_user',
        ),
    ]
